## <div style="text-align: center;"><span style="font-style: italic; color: #FFACD8;">Gaussian Elimination Algorithm On 3 X 3 Singular and Non-Singular Matrix </span></div>

In [199]:
import numpy as np

# Stage 1: Linear Equations and Equation Coefficient

In [148]:
equation_1 = list(map(int,input("Enter the 1st equation").split()))
equation_2 = list(map(int,input("Enter the 2nd equation").split()))
equation_3 = list(map(int,input("Enter the 3rd equation").split()))

print(f"{equation_1[0]}a + {equation_1[1]}b + {equation_1[2]}c = {equation_1[-1]}")
print(f"{equation_2[0]}a + {equation_2[1]}b + {equation_2[2]}c = {equation_2[-1]}")
print(f"{equation_3[0]}a + {equation_3[1]}b + {equation_3[2]}c = {equation_3[-1]}")

Enter the 1st equation 2 -1 1 1
Enter the 2nd equation 2 2 4 -2 
Enter the 3rd equation 4 1 0 -1


2a + -1b + 1c = 1
2a + 2b + 4c = -2
4a + 1b + 0c = -1


# Stage 2: Matrix, Vector and Augmented Matrix 

In [162]:
N = np.hstack((equation_1[0:3],equation_2[0:3],equation_3[0:3]), dtype = float).reshape(3,3)
print(f"Converting the System of Linear Equations to:\n 1) Matrix N \n{N}")
n = np.hstack((equation_1[-1],equation_2[-1],equation_3[-1]), dtype = float).reshape(3,1)
print(f"\n 2) Vector n \n{n}")

Converting the System of Linear Equations to:
 1) Matrix N 
[[ 2. -1.  1.]
 [ 2.  2.  4.]
 [ 4.  1.  0.]]

 2) Vector n 
[[ 1.]
 [-2.]
 [-1.]]


In [163]:
def augmented_matrix(A,B):
    augmented_N = np.hstack((A,B))
    return augmented_N

In [164]:
print(f"Augmented Matrix N :\n {augmented_matrix(N,n)}")

Augmented Matrix N :
 [[ 2. -1.  1.  1.]
 [ 2.  2.  4. -2.]
 [ 4.  1.  0. -1.]]


# Stage 3: Row Echlon Form Functions 

1) swap function
2) find first non-zero in a column
3) find the first non-zero in a row (Pivot)
4) define the Row Echlon Form Function
5) define back substitution function
6) define Gaussian Elimination function

In [167]:
def swap_rows(M,row_index1,row_index2):
    M = M.copy()
    M[[row_index1,row_index2],:]=M[[row_index2,row_index1],:]
    return M

In [168]:
def swap_cols(M, col_index1, col_index2):
    M = M.copy()
    M[:,[col_index1,col_index2]] = M[:,[col_index2,col_index1]]
    return M

In [169]:
def get_index_first_non_zero_value_from_column(M, starting_row, column):
    col_array = M[starting_row : , column]

    for i , val in enumerate(col_array):
        if not np.isclose(val , 0 , atol = 1e-5):
            index = starting_row + i
            return index 
    return -1 

In [170]:
def get_index_first_non_zero_value_from_row(M, row, augmented = False):

    M = M.copy()
    
    if augmented == True:
        M[:,:-1]

        row_array = M[row]
        for i, val in enumerate(row_array):
            if not np.isclose(val , 0, atol = 1e-5):
                return i
        return -1 

In [186]:
def row_echlon_form(A,B):
    A = A.copy()
    B = B.copy()
    A = A.astype('float64')
    A = A.astype('float64')
        
    num_rows = len(A)
    det_A = np.linalg.det(A)
    if not np.isclose(det_A, 0, atol = 1e-5):
        print("Matrix is Singular")

    M = augmented_matrix(A,B)

    for row in range(num_rows):
        pivot_candidate = M[row,row]

        if pivot_candidate == 0 :
            first_non_zero_value_below_pivot_candidate = get_index_first_non_zero_value_from_column(M, row, row)
            if first_non_zero_value_below_pivot_candidate == -1:
                index = get_index_first_non_zero_value_from_row(M,row,augmented = True)
                if index == -1:
                    if not np.isclose(M[row,-1], 0, atol = 1e-5):
                        print("Matrix is Singular and has no Solution")
                    else:
                        print("Matrix is Singular and has infinite Solutions")
                    break
                else:
                    M = swap_cols(M, row, index)
                
            M = swap_rows(M, row, first_non_zero_value_below_pivot_candidate)
            
            pivot = M[row,row]
            
        else:
            pivot = pivot_candidate 

        M[row] = (1/pivot) * M[row]

        for j in range (row+1 , num_rows):
            value_below_pivot = M[j,row]
            M[j] = M[j] - (value_below_pivot * M[row])
                
    return M 

In [187]:
def back_substitution(M):
    
    det_A = np.linalg.det(M[:, :-1])
    if np.isclose(det_A, 0, atol = 1e-5):
        return None

    M = M.copy()

    num_of_rows = M.shape[0]

    for row in reversed (range(num_of_rows)):

        subsitiution_row = M[row]
        index = get_index_first_non_zero_value_from_row(M,row, augmented = True)

        for j in range (row):

            row_to_reduce = M[j]
            value = row_to_reduce[index]

            row_to_reduce = row_to_reduce - subsitiution_row * value

            M[j, :] = row_to_reduce 

    solution = M[:, -1]
    solution[np.abs(solution) == 0] = 0
    
    return solution
            

In [188]:
def Gaussian_Elimination(A, B):
    det_A = np.linalg.det(A)
    row_echlon_form_matrix = row_echlon_form(A,B)
    
    if not np.isclose (det_A, 0, atol = 1e-5):
        gaussian_elimination = back_substitution(row_echlon_form_matrix)
        print("Solution for the Linear System is: ")
        print(f"x = {gaussian_elimination[0]}\ny = {gaussian_elimination[1]}\nz = {gaussian_elimination[2]}")
        
    else:
        return row_echlon_form_matrix

In [189]:
Gaussian_Elimination(N, n)

Matrix is Singular
Solution for the Linear System is: 
x = 0.0
y = -1.0
z = 0.0


### Extra Examples of Singular Matrices 

In [194]:
A =np.array( [[1, 2, 3],
     [2, 4, 6],
     [0, 1, 2]])
B = np.array([[1],
     [2],
     [3]])

In [195]:
Gaussian_Elimination(A, B)

Matrix is Singular and has infinite Solutions


array([[1., 2., 3., 1.],
       [0., 1., 2., 3.],
       [0., 0., 0., 0.]])

In [196]:
C = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 2, 3]])

D = np.array([[1],
              [2],
              [5]])

In [198]:
Gaussian_Elimination(C, D)

Matrix is Singular and has infinite Solutions


array([[1., 2., 3., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 4.]])

## <span style="font-style: italic; color: #F67BB6;">Et voilà ! <3</span>